### ISSUE TITLE
May I ask where the matplotlib code in the input comes from?

### ISSUE THREAD

**Issue by wwzhuang01** [Yushi-Hu/VisualSketchpad#2]
Great job! I have a question about the Geometry Problems in Section 4, Sketching to Solve Math Problems, where you mentioned that SKETCHPAD takes a geometry diagram and its corresponding matplotlib code as input. How did you obtain the matplotlib code for the images in the Geometry3K dataset?

**Comment by Yushi-Hu** [comment]
Thanks for your interest in our work! We will release codes and data in early July. Geometry 3K has the coordinates for each point, so we use GPT-4V + human edits to manually write all the codes for the images, which takes many human effort. We will update them soon!

**Comment by va1shn9v** [comment]
Hello, Amazing Project. I wanted to try this out, may I know when would the codes be released. Thanks for you work.

**Comment by Yushi-Hu** [comment]
we are working towards to release it in a week
