### ISSUE TITLE
Do We Need to Input Matplotlib Code for Geometry Problems?

### ISSUE THREAD

**Issue by jweihe** [Yushi-Hu/VisualSketchpad#3]
I was wondering whether it is necessary to input the geometric shapes using Matplotlib code? Additionally, how is this code typically generated or obtained?

Any guidance on this matter would be greatly appreciated. Thank you!

**Comment by Yushi-Hu** [comment]
Yes. Sorry I am really busy last month. I am cleaning the codes now and it
will be clearer on how to generate codes. Hopefully release soon!

**Comment by Yushi-Hu** [comment]
The codes for the matplotlib plots are generated by gpt4, and we manually cleaned them. We have released them in the GitHub.

**Comment by jweihe** [comment]
Thank you for your response! Could you provide an example of the prompt you used to generate Matplotlib code with GPT-4? I’ve tried generating it automatically but didn’t get great results. Any example or guidance would be greatly appreciated.

**Comment by Yushi-Hu** [comment]
@swj0419 would you please share some prompts?

According to my impression, yes the quality of GPT-4 is pretty low for this task. It can be greatly improved if you provide some in-context code examples for GPT-4

**Comment by jweihe** [comment]
Thanks, for your insights on the quality of GPT-4 for generating Matplotlib code. I agree that providing in-context code examples can significantly improve the results. Looking forward to seeing the prompts shared by @swj0419.

**Comment by hihihihiwsf** [comment]
Hi, has the prompt for generating Matplotlib code been shared? I also couldn't find it anywhere in this repo.
