### ISSUE TITLE
detection always shows IndexError: string index out of range Please fix the error and generate the fixed code, in the next THOUGHT and ACTION.

### ISSUE THREAD

**Issue by BobbyPeng123** [Yushi-Hu/VisualSketchpad#5]
When I'm testing your system with vstar dataset, when it want to detect it always shows IndexError: string index out of range
Please fix the error and generate the fixed code, in the next THOUGHT and ACTION. and then turn to use SAM. Is this normal?

**Comment by The-Martyr** [comment]
> When I'm testing your system with vstar dataset, when it want to detect it always shows IndexError: string index out of range Please fix the error and generate the fixed code, in the next THOUGHT and ACTION. and then turn to use SAM. Is this normal?

Hi, I would like to know how you solved this problem?
